spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=hCMdSpWeMIn1UhHJd0d9fsNQEanV6BZ5VVQm7wlTqtF
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000

rate-limit.capacity=50
rate-limit.refill-amount=50
rate-limit.refill-period-seconds=60
