# ===== UAT — PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/fortknox_uat
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:hCMdSpWeMIn1UhHJd0d9fsNQEanV6BZ5VVQm7wlTqtF}
jwt.access-token-expiry=900000
jwt.refresh-token-expiry=604800000

rate-limit.capacity=100
rate-limit.refill-amount=100
rate-limit.refill-period-seconds=60
